### ISSUE TITLE
Old glitches (Already patched) - (1.0.2)

### ISSUE THREAD

**Issue by shadowTW** [finalLy134/qb-activeofficers#3]
![image](https://user-images.githubusercontent.com/64441627/169646148-8fa9e6a7-02a4-4978-bc22-22e861db9b79.png)

**Comment by finalLy134** [comment]
Try to restart the script and tell me what happens.

**Comment by finalLy134** [comment]
Try it now, I've updated what I can
Tell me if it works.

**Comment by finalLy134** [comment]
Also make sure you have all the script's requirements set up!

**Comment by finalLy134** [comment]
I've just fixed it, update your client.lua

**Comment by finalLy134** [comment]
Try to restart your script through the F8

**Comment by finalLy134** [comment]
Oh I forgot to tell you I've changed it again
Update it, Sorry :)

**Comment by finalLy134** [comment]
NP thank you for reporting about these problems!
You really helped me! :)
