### ISSUE TITLE
when entering the server while i am a "police" as a job i get the following error

### ISSUE THREAD

**Issue by dvaturi** [finalLy134/qb-activeofficers#4]
![image](https://user-images.githubusercontent.com/57751780/169665072-5771b530-41ee-481b-bf0b-c3e3ed16be30.png)

**Comment by ZEEVI1** [comment]
Hi man if ur using the esx version, can u please send me a working link for download?
thanks

**Comment by finalLy134** [comment]
I know, I'm already trying to fix it
I'll let you know once it's fixed

**Comment by finalLy134** [comment]
The toggle buttons were removed for now
It'll be fixed in a couple days.
Sorry about it - but I want some days to look into it.

**Comment by finalLy134** [comment]
Fixed in the new version!
